"""
pipeline.py
BookWorld data pipeline: extracts, transforms, and loads sales data from multiple sources
(CSV, SQLite, web scraping, exchange rate API) into a final aggregated dataset (sales by country).
"""

import pandas as pd
import sqlite3
import requests
import textwrap
import os
from bs4 import BeautifulSoup
from urllib.parse import urljoin

# Display options: show all columns and avoid line wrapping in the terminal
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

# Path to the SQLite reference database (already populated with business reference tables:
# category_rules, channels, countries
DB_NAME = "data/bookworld_reference.db"

# Folder for all files generated by this pipeline (queries.sql, final_batabase.db)
OUTPUT_DIR = "output_pipeline"

# Path to the website to scrap (first page only, as required by the exam)
BOOKSTOSCRAP_URL = "https://books.toscrape.com/"


def extract():
    """
    Extract raw data from the CSV file, the SQLite reference database,
    and the book catalog (1st page of books.toscrape.com).
    """

    # Sales data (CSV) Read "sales_raw.csv" file store it as df_sales_raw
    try:
        df_sales_raw = pd.read_csv("data/sales_raw.csv", encoding="utf-8")
        ## print(df_sales_raw.shape)
        ## print(df_sales_raw.head())
    except FileNotFoundError:
        print("Error: data/sales_raw.csv not found")
        raise
    except Exception as e:
        print(f"Unexpected error while reading the CSV file: {e}")
        raise

    # Bookworld reference data (SQLite) Open a connexion to the reference database
    try:
        conn = sqlite3.connect(DB_NAME)
    except sqlite3.Error as e:
        print(f"Error: could not connect to the reference database ({DB_NAME}): {e}")
        raise


    def run_query(label, query, conn):
        """
        Run a SQL query against the given connection and return the result as
        a DataFrame. Centralizes the try/except pattern repeated for every
        SQLite read in extract(), so each call site only needs to provide a
        label (for error messages) and the query itself.
        """
        try:
            return pd.read_sql_query(query, conn)
        except Exception as e:
            print(f"Error while reading '{label}': {e}")
            conn.close()
            raise

    # category_rules: margin rate, strategic flag and sales status per book category
    query_category_rules = "SELECT * FROM category_rules"
    df_category_rules = run_query("category_rules", query_category_rules, conn)

    # channels: acquisition cost, grouping and active status per sales channel
    query_channels = "SELECT * FROM channels"
    df_channels = run_query("channels", query_channels, conn)

    # countries: currency, VAT rate and active status per country
    query_countries = "SELECT * FROM countries"
    df_countries = run_query("countries", query_countries, conn)

    # Query with a filter: keep only is_active = 1
    query_category_rules_is_active = "SELECT * FROM category_rules WHERE is_active = 1"
    df_category_rules_is_active = run_query(
        "category_rules (is_active=1)", query_category_rules_is_active, conn
    )

    query_channels_is_active = "SELECT * FROM channels WHERE is_active = 1"
    df_channels_is_active = run_query(
        "channels (is_active=1)", query_channels_is_active, conn
    )

    query_countries_is_active = "SELECT * FROM countries WHERE is_active = 1"
    df_countries_is_active = run_query(
        "countries (is_active=1)", query_countries_is_active, conn
    )

    # Enrichment query (join): category_rules and channels
    query_join_cat_rules_and_channels = """
        SELECT
            cr.category_name,
            cr.default_channel_code,
            cr.is_active AS is_active_cat_rules,
            cr.margin_rate,
            cr.strategic_flag,
            c.acquisition_cost_gbp,
            c.channel_code,
            c.channel_group,
            c.channel_name,
            c.is_active AS is_active_channels
        FROM category_rules cr
        JOIN channels c
            ON c.channel_code = cr.default_channel_code
    """
    df_join_cat_rules_and_channels = run_query(
        "join category_rules/channels", query_join_cat_rules_and_channels, conn
    )

    # Close the connection once all reference tables have been read
    conn.close()

    # --- Generate queries.sql from the queries actually used above ---
    # Each entry is (documentation comment, SQL query variable). Building the
    # file here, from the same variables that were actually executed, keeps
    # it in sync with the real pipeline logic instead of a separate,
    # hand-written copy that could drift out of date.
    queries_documentation = [
        (
            "Full category_rules table: margin rate, strategic flag and "
            "default sales channel per book category",
            query_category_rules,
        ),
        (
            "Full channels table: acquisition cost and grouping per sales channel",
            query_channels,
        ),
        (
            "Full countries table: currency, VAT rate and active status per country",
            query_countries,
        ),
        (
            "Query with a filter: only the active book categories (is_active = 1). "
            "One category (Horror) is currently marked inactive.",
            query_category_rules_is_active,
        ),
        (
            "Enrichment query: joins category_rules with its default sales channel, "
            "to know the acquisition cost and grouping of the channel each category "
            "is normally sold through. Columns are explicitly aliased to avoid "
            "ambiguity between the two 'is_active' columns (one per table).",
            query_join_cat_rules_and_channels,
        ),
    ]

    try:
        os.makedirs(OUTPUT_DIR, exist_ok=True)
        with open(f"{OUTPUT_DIR}/queries.sql", "w", encoding="utf-8") as f:
            f.write("-- queries.sql\n")
            f.write("-- BookWorld project - SQL queries used to extract data from bookworld_reference.db\n")
            f.write("-- Auto-generated by pipeline.py (extract()) - do not edit by hand\n\n")
            for doc, query in queries_documentation:
                f.write(f"-- {doc}\n")
                f.write(textwrap.dedent(query).strip() + ";\n\n")

    except OSError as e:
        print(f"Error: could not write queries.sql: {e}")
        raise

    # Books to Scrape catalog (Web scrapping, 1st page only)
    try:
        response = requests.get(BOOKSTOSCRAP_URL)
        # Force UTF-8 decoding : requests sometimes guesses the wrong encoding from the response headers,
        # which corrupts special characters like "£"
        response.encoding = "utf-8"
    except requests.exceptions.RequestException as e:
        print(f"Error: could not reach the catalog page ({BOOKSTOSCRAP_URL}): {e}")
        raise

    soup = BeautifulSoup(response.text, "html.parser")

    # Each book on the 1st page is wrapped in <article class = "product_pod">
    books = []
    for product in soup.find_all("article", class_="product_pod"):
        # Reset at the start of each iteration - to avoid conflict with except block
        title = None

        try:
            # Title is store in the "title" attribute of the <a> tag inside <h3>
            title = product.h3.a["title"]

            # href is a relative link (e.g. "catalogue/a-light-in-the-attic_1000/index.html") 
            # urljoin combines it with the base URL to get an absolute URL
            relative_url = product.h3.a["href"]
            book_url = urljoin(BOOKSTOSCRAP_URL, relative_url)

            # Explore book's detail page to retreive data
            detail_response = requests.get(book_url)
            detail_response.encoding = "utf-8"
            detail_soup = BeautifulSoup(detail_response.text, "html.parser")

            # Scope 1: <div class="col-sm-6 product_main"> holds:
            # price, stock, status and star rating for THE CURRENT book.
            product_main = detail_soup.find("div", class_="col-sm-6 product_main")

            # Price is the text content of <p class="price_color">, e.g. "£47.82"
            price_text = product_main.find("p", class_="price_color").text
            price_gbp = float(price_text.replace("£", ""))

            # Availability text, e.g. "In stock (22 available)"
            availability = product_main.find("p", class_="instock availability").text.strip()

            # Star rating is encoded as a CSS class on <p class="star-rating Three">
            # (word form: One, Two, Three, Four, Five), not as visible text
            rating_words = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}
            rating_tag = product_main.find("p", class_="star-rating")
            rating = rating_words[rating_tag["class"][1]]

            # Scope 2: <table class="table table-striped"> holds:
            # UPC, prices, tax and review count.
            # Row order on this site is always:
            # UPC, Product Type, Price (excl. tax), Price (incl. tax), Tax, Availability, Number of reviews
            table = detail_soup.find("table", class_="table table-striped")
            rows = table.find_all("tr")
            upc = rows[0].find("td").text.strip()
            price_excl_tax = rows[2].find("td").text.strip()
            price_incl_tax = rows[3].find("td").text.strip()
            tax = rows[4].find("td").text.strip()
            number_of_reviews = rows[6].find("td").text.strip()

            # Category comes from the breadcrumb, outside product_main:
            # "Home > Books > Category > Book title" -> the 3rd <a> (index 2)
            breadcrumb = detail_soup.find("ul", class_="breadcrumb")
            category = breadcrumb.find_all("a")[2].text.strip()

            books.append({
                "book_name": title,
                "price_gbp": price_gbp,
                "book_url": book_url,
                "category": category,
                "upc": upc,
                "price_excl_tax": price_excl_tax,
                "price_incl_tax": price_incl_tax,
                "tax": tax,
                "number_of_reviews": number_of_reviews,
                "availability": availability,
                "rating": rating,
            })
        except Exception as e:
            # title may still be None if the failure happened before it was read
            book_label = title if title is not None else "unknown book"
            print(f"Warning: could not scrape book '{book_label}', skipping it: {e}")
            continue


    df_catalog = pd.DataFrame(books)

    # Exchange rate (Frankfurter API)
    # v2/rate/{base}/{quote} returns a flat response for a single currency pair
    last_exchange_rates_url = "https://api.frankfurter.dev/v2/rate/GBP/EUR"

    try:
        response_rate = requests.get(last_exchange_rates_url)
        data_rate = response_rate.json()
        gbp_to_eur = data_rate["rate"]
    except requests.exceptions.RequestException as e:
        # The exchange rate service is unreachable (network, issue, timeout...)
        print(f"Error: could not reach the exchange rate API ({last_exchange_rates_url}): {e}")
        raise
    except (ValueError, KeyError) as e:
        # Valid requests.get() but response not JSON or
        # did not contain the expected "rate" key (unexepected API response shape)
        print(f"Error: unexpected exchange rate API response: {e}")
        raise
    # For consistency, single-row API response convert in a DataFrame
    df_exchange_rate = pd.DataFrame([data_rate])

    data = {
        "sales_raw": df_sales_raw,
        "category_rules": df_category_rules,
        "channels": df_channels,
        "countries": df_countries,
        "book_catalog": df_catalog,
        "exchange_rate": df_exchange_rate,
    }
    return data

def transform(data):
    """
    Clean, enrich and aggregate the raw data extracted by extract() into
    the final sales_by_country dataset.
    """
    df_sales_raw = data["sales_raw"]
    df_category_rules = data["category_rules"]
    df_channels = data["channels"]
    df_countries = data["countries"]
    df_catalog =  data["book_catalog"]
    df_exchange_rate = data["exchange_rate"]


    # Data quality checks: missing values, duplicates, general info
    dataframes = {
    "df_sales_raw": df_sales_raw,
    "df_category_rules": df_category_rules,
    "df_channels": df_channels,
    "df_countries": df_countries,
    "df_catalog": df_catalog,
    "df_exchange_rate": df_exchange_rate,
    }

    for name, df in dataframes.items():
        missing_count = df.isna().sum().sum()
        duplicate_count = df.duplicated().sum()

        if missing_count > 0:
            print(f"Warning: {name} has {missing_count} missing value(s):\n{df.isna().sum()}")
        if duplicate_count > 0:
            print(f"Warning: {name} has {duplicate_count} duplicate row(s)")
        if name == "df_sales_raw":
            dup_order_id = df.duplicated(subset="order_id").sum()
            if dup_order_id > 0:
                print(f"Warning: {dup_order_id} duplicate order_id found in df_sales_raw")
        elif name == "df_catalog":
            dup_book_name = df.duplicated(subset="book_name").sum()
            if dup_book_name > 0:
                print(f"Warning: {dup_book_name} duplicate book_name found in df_catalog")

    # Enrichment: merge df_sales_raw with the scraped df_catalog
    # Check shared column names first
    common_columns_btw_sales_raw_and_catalog = set(df_sales_raw.columns) & set(df_catalog.columns)
    if common_columns_btw_sales_raw_and_catalog:
        print(f"List of common columns between df_sales_raw and df_catalog: {common_columns_btw_sales_raw_and_catalog}")

    # "left" keeps every sales, even if its book is missing from the catalog.
    df_sales_merged = df_sales_raw.merge(df_catalog, how="left", on="book_name")
    sales_without_catalog_match = df_sales_merged["price_gbp"].isna().sum()
    if sales_without_catalog_match > 0:
        print(f"Warning: {sales_without_catalog_match} sale(s) have no matching book in the catalog")

    # Data quality check: reference rows marked inactive, but still sold.
    # Some rows in the reference data are marked is_active = 0 (e.g. Portugal
    # in countries, "Horror" in category_rules), yet sales for them may still
    # exist. Rather than silently dropping these sales, we flag the issue so
    # it's visible and can be discussed/justified in the final report.
    inactive_country_codes = df_countries.loc[df_countries["is_active"] == 0, "country_code"].tolist()
    countries_in_sales = df_sales_merged["country_code"].unique().tolist()
    inactive_countries_with_sales = [c for c in inactive_country_codes if c in countries_in_sales]
    if inactive_countries_with_sales:
        print(f"Warning: sales found for countries marked inactive in the reference data: {inactive_countries_with_sales}")
 
    inactive_category_names = df_category_rules.loc[df_category_rules["is_active"] == 0, "category_name"].tolist()
    categories_in_sales = df_sales_merged["category"].dropna().unique().tolist()
    inactive_categories_with_sales = [c for c in inactive_category_names if c in categories_in_sales]
    if inactive_categories_with_sales:
        print(f"Warning: sales found for categories marked inactive in the reference data: {inactive_categories_with_sales}")
 
    # Revenue per sale line.
    # discount_rate is a discount rate (e.g. 0.15 = 15% off), so it must be
    # applied as (1 - discount_rate), not multiplied directly.
    df_sales_merged["revenue_gbp"] = df_sales_merged["quantity"] * df_sales_merged["price_gbp"] * (1 - df_sales_merged["discount_rate"])

    # Aggregate sales by country.
    df_sales_by_country = df_sales_merged.groupby("country_code").agg(
        total_orders=("order_id", "count"),
        total_quantity=("quantity", "sum"),
        total_revenue_gbp=("revenue_gbp", "sum"),
    ).reset_index()

    # Add country_name by joining with the countries reference table
    df_sales_by_country = df_sales_by_country.merge(
        df_countries[["country_code", "country_name"]], how="left", on="country_code"
    )

    # Data quality check: country codes with sales but no entry at all in the
    # reference table (no row, not even inactive). No reference data.
    missing_reference_countries = df_sales_by_country.loc[
        df_sales_by_country["country_name"].isna(), "country_code"
    ].tolist()
    if missing_reference_countries:
        print(f"Warning: country codes with sales but no entry at all in the reference data: {missing_reference_countries}")
    df_sales_by_country["country_name"] = df_sales_by_country["country_name"].fillna("Unknown")

    # Convert GBP revenue to EUR using the exchange rate fetched from the API.
    gbp_to_eur = df_exchange_rate["rate"].iloc[0]
    df_sales_by_country["total_revenue_eur"] = df_sales_by_country["total_revenue_gbp"] * gbp_to_eur

    # Reorder columns to match the exam's expected structure.
    df_sales_by_country = df_sales_by_country[[
        "country_code", "country_name", "total_orders", "total_quantity",
        "total_revenue_gbp", "total_revenue_eur",
    ]]

    # Build the RGPD-compliant "sales" table for the final database.
    # Only the columns needed downstream are kept: no customer_first_name /
    # customer_last_name (RGPD)
    df_sales_final = df_sales_merged[[
        "order_id", "order_date", "book_name", "country_code",
        "channel_code", "quantity", "discount_rate", "revenue_gbp"
    ]]

    # All final tables to be written to the database by load()
    results = {
        "channels": df_channels,
        "countries": df_countries,
        "category_rules": df_category_rules,
        "book_catalog": df_catalog,
        "sales": df_sales_final,
        "exchange_rate": df_exchange_rate,
        "sales_by_country": df_sales_by_country,
    }
    return results

def load(results, db_path=f"{OUTPUT_DIR}/bookworld_final.db", schema_path="schema_final.sql"):
    """
    Create the final database from schema_final.sql (if not already created)
    and load each cleaned/aggregated DataFrame into its matching table.
    """
    try:
        os.makedirs(OUTPUT_DIR, exist_ok=True)
        conn = sqlite3.connect(db_path)
        conn.execute("PRAGMA foreign_keys = ON")
    except (OSError, sqlite3.Error) as e:
        print(f"Error: could not connect to the final database ({db_path}): {e}")
        raise

    try:
        with open(schema_path, encoding="utf-8") as f:
            conn.executescript(f.read())
    except (OSError, sqlite3.Error) as e:
        print(f"Error: could not create schema from {schema_path}: {e}")
        conn.close()
        raise

    # Parent tables (referenced by a FOREIGN KEY) must be loaded before the
    # tables that reference them, otherwise the FK check fails on insert.
    table_order = [
        "channels",
        "countries",
        "category_rules",
        "book_catalog",
        "sales",
        "exchange_rate",
        "sales_by_country",
    ]

    for table_name in table_order:
        df = results[table_name]
        try:
            df.to_sql(table_name, conn, if_exists="append", index=False)
            print(f"Loaded {len(df)} rows into '{table_name}'")
        except Exception as e:
            print(f"Error while loading table '{table_name}': {e}")
            conn.close()
            raise

    conn.commit()
    conn.close()
    print(f"Final database written to {db_path}")

if __name__ == "__main__":
    data = extract()
    results = transform(data)
    load(results)
