-- queries.sql
-- BookWorld project - SQL queries used to extract data from bookworld_reference.db
-- Auto-generated by pipeline.py (extract()) - do not edit by hand

-- Full category_rules table: margin rate, strategic flag and default sales channel per book category
SELECT * FROM category_rules;

-- Full channels table: acquisition cost and grouping per sales channel
SELECT * FROM channels;

-- Full countries table: currency, VAT rate and active status per country
SELECT * FROM countries;

-- Query with a filter: only the active book categories (is_active = 1). One category (Horror) is currently marked inactive.
SELECT * FROM category_rules WHERE is_active = 1;

-- Enrichment query: joins category_rules with its default sales channel, to know the acquisition cost and grouping of the channel each category is normally sold through. Columns are explicitly aliased to avoid ambiguity between the two 'is_active' columns (one per table).
SELECT
    cr.category_name,
    cr.default_channel_code,
    cr.is_active AS is_active_cat_rules,
    cr.margin_rate,
    cr.strategic_flag,
    c.acquisition_cost_gbp,
    c.channel_code,
    c.channel_group,
    c.channel_name,
    c.is_active AS is_active_channels
FROM category_rules cr
JOIN channels c
    ON c.channel_code = cr.default_channel_code;

